### ISSUE TITLE
lean-conky closes when I click on the desktop

### ISSUE THREAD

**Issue by mexsudo** [jxai/lean-conky-config#1] opened 2021-04-10 15:20 UTC
lean-conky closes when I click on the desktop
running Debian Bullseye Mate.
installed lean-conky from the Excellent instructions in your Wiki README.md
I have made no changes
everything works just great but lean-conky closes when I click on any free space on the desktop
it restarts with no issue
what can I do on my end?

Thanks!

**Comment by jxai** [comment] 2021-04-27 04:47
@mexsudo how do you start conky with LCC? Also, do you have this issue with other conky configs?

**Comment by scamdotnet** [comment] 2021-04-27 12:10
I also have this same issue, on my raspberry pi 400 running raspberry pi os. I installed conky using pi-apps, which came with a default config, which didn't have this issue. For me conky is started automatically by the script provided in the pi-apps version of conky.

**Comment by jxai** [comment] 2021-04-29 03:55
Start from console:
```
conky -c /path/to/lean-conky-config/conky.conf
```
When the issue occurs and Conky closes by itself, do you see any informative log?

**Comment by scamdotnet** [comment] 2021-04-29 15:09
> ```
> conky -c /path/to/lean-conky-config/conky.conf
> ```

it appears the proccess doesn't close, it just hides the window, and no messages appear in the log. There are some messages, but they show up before i click on the desktop. Here they are:
```
$ conky -c .config/conky/conky.conf
conky: warning: invalid head index, ignoring head settings
conky: warning: invalid head index, ignoring head settings
conky: desktop window (e00003) is subwindow of root window (372)
conky: window type - desktop
conky: drawing to created window (0x4000002)
conky: drawing to double buffer

```

**Comment by jxai** [comment] 2021-05-01 17:18
@scamdotnet What is the your desktop environment and version? and conky version?

**Comment by scamdotnet** [comment] 2021-05-01 17:56
> @scamdotnet What is the your desktop environment and version? and conky version?

LXDE 10, and Conky 1.10.8

**Comment by jxai** [comment] 2021-05-02 08:24
@scamdotnet It is a known issue of Conky on LXDE, not LCC's, please check out the discussion [here](https://askubuntu.com/questions/181663/how-to-get-conky-to-stay-on-the-desktop).

@mexsudo Not sure if the cause of your issue is the same, I didn't test on MATE, you might try Conky's default config:
```bash
conky -c /etc/conky/conky.conf
```
If you have the same issue, then Conky doesn't play well with your desktop environment.

**Comment by jxai** [comment] 2021-05-02 08:28
@mexsudo Not sure if your have

**Comment by jxai** [comment] 2021-05-02 10:41
> > @scamdotnet What is the your desktop environment and version? and conky version?
> 
> LXDE 10, and Conky 1.10.8

Should be fixed now.

**Closed as completed** 2021-05-02 10:41 UTC

**Comment by mexsudo** [comment] 2021-05-02 12:41
Pardon me for not responding earlier.
I use a Mate toolbar launcher:  /home/peter/.config/conky/lean-conky-config-master/start.sh
I just download the ZIP again it is now working as expected. 
Thanks.

**Comment by eddybeliveau** [comment] 2023-07-04 21:12
Hi!
I am using the leatest LCC, it work well on Ubuntu 22.04.2 LTS. Thanks
I copied the local.conf.example to local.conf and try to custom it.  
but I cannot find the way to add the lsb_release on the kernel line

Where can I find the source of the lcc.panel 'system' component ?
or can I custom the 'system' component panel directly in local.conf

I would like to obtain the equivalent of:
$(kernel)  $(execi 999999 lsb_release -ds) $(alignr) $(machine)

sorry for the parenthesis, I don't have the correct character on this keyboard.

Thanks and have a nice day

**Comment by eddybeliveau** [comment] 2023-07-05 19:00
Solution: edit $HOME/.config/conky/lib/components/core.lua
replace the kernel line within llc.tpl.system section by
${font}${sysname} ${kernel}   ${execi 999999 lsb_release -ds}${alignr}${machine}

restart conky and voila!
