### ISSUE TITLE
The visual display of network speed data failed.

### ISSUE THREAD

**Issue by AntsCodeCommunity** [jxai/lean-conky-config#12] opened 2023-02-27 04:48 UTC
![LCC-CONKY-BUG](https://user-images.githubusercontent.com/70638841/221476716-30457ab5-abd5-4da8-8ebc-fad2b5492922.png)

**Comment by Zeggpold** [comment] 2023-03-07 22:21
Maybe caused by [this conky bug](https://github.com/brndnmtthws/conky/issues/1109), which unfortunately seems to have been closed without being fixed.

**Comment by jxai** [comment] 2023-03-31 07:38
Duplicate of #8

**Comment by jxai** [comment] 2023-03-31 07:39
Duplicate of #8

**Closed as not planned by jxai** 2023-03-31 07:39 UTC
